### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by powtac** [ka-ka-xyz/atom-charcode#2]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
<unknown> (/Users/simonbruchner/.atom/packages/atom-charcode/lib/atom-charcode-view.coffee:12:28)
```

**Comment by ka-ka-xyz** [comment]
Thank you for reporting this issue. Fixed in 03a23a394a8eadb7a03c091827fa1df1c5849e28.
